language: node_js

node_js:
- 6
- 8
- 10

branches:
  only:
    - master

matrix:
  include:
    - node_js: 4
      script: npm test # can't run eslint in node 4

script:
  - npm run lint:js
  - npm test
